/**
 * @module
 *
 * On-disk SENTINEL for the `virtual:treaty-routes` import under Rspack/webpack.
 *
 * The bare `virtual:treaty-routes` specifier is aliased to this file so the bundler
 * can resolve it to a real module; the routes loader (matched to this file) then
 * REPLACES the source below with the routes module generated by the Rust
 * file-routing core. This default export is therefore never emitted into a build —
 * it exists only to keep type/lint tooling and a no-loader resolution from seeing an
 * empty module, and to make the file's purpose explicit.
 */

/** Placeholder route list; overwritten at build time by the routes loader. */
export const routes: never[] = []
export default routes
