//! TypeScript route-module emission for [`crate::GeneratedRouting`].
//!
//! This is the *single* emitter shared by every host that needs a ready-to-import
//! TypeScript routes module: the `treaty-file-routing` CLI (`--emit ts`) and the
//! NAPI binding the bundler plugins call to produce the file-routing **virtual
//! module** during a build. Keeping the lowering in one place (here, in the pure
//! core) is the same Rust-core / thin-shim layering the rest of Treaty follows —
//! logic ONCE in Rust, no duplication between the CLI and the addon. See
//! [[rust-core-ts-shim-layering]].
//!
//! The output is byte-for-byte deterministic for a given routing + import base:
//! [`crate::generate_routing`] sorts every listing and emits in a stable order,
//! and the rendering here is a fixed-order walk with hand-rendered indentation.

use crate::config::{AngularRoute, FederationRemote, GeneratedRouting};

/// File banner for the emitted TypeScript module.
const TS_BANNER: &str = "\
// GENERATED by Treaty file routing — DO NOT EDIT.
//
// File-system routes lowered from the routes/ tree by the treaty_file_routing
// crate (libs/file-routing): an Angular `Routes` array of lazy `loadComponent`
// boundaries plus the Module Federation remote descriptors. Produced as a build
// virtual module by the bundler plugins (or by the CLI `--emit ts`); never
// checked in.
";

/// Doc comment preceding the `federationRemotes` export.
const REMOTES_DOC: &str = "\
/**
 * Module Federation remotes derived from the lazy route + layout boundaries.
 * Every lazy route and layout boundary is one remote (`exposedModule: './Route'`);
 * names are globally unique, de-duplicated in emission order.
 */
";

/// Render the [`GeneratedRouting`] as a self-contained, ready-to-import
/// TypeScript module: an Angular `Routes` array of lazy `loadComponent`
/// boundaries (nesting layout parents over their `children`) plus the Module
/// Federation `federationRemotes` descriptor array.
///
/// `import_base` is prefixed to each tree-relative entry file in the emitted
/// `import(...)` loaders (e.g. `../../`, i.e. resolving `routes/foo.treaty` from
/// a `src/generated/` module; or a virtual-module-relative base for a bundler
/// plugin). The output is byte-for-byte deterministic for a given routing + base.
pub fn emit_ts(routing: &GeneratedRouting, import_base: &str) -> String {
    let mut s = String::new();
    s.push_str(TS_BANNER);
    s.push_str("import type { Routes } from '@angular/router'\n\n");
    s.push_str("/** The Angular route graph generated from the routes/ directory tree. */\n");
    s.push_str("export const routes: Routes = [\n");
    for route in &routing.routes {
        emit_route(&mut s, route, import_base, 1);
    }
    s.push_str("]\n\nexport default routes\n\n");

    s.push_str(REMOTES_DOC);
    s.push_str("export const federationRemotes = ");
    emit_remotes(&mut s, &routing.remotes);
    s.push_str(" as const\n");
    s
}

/// The set of tree-relative entry files an emitted module's `import(...)` loaders
/// reference, in emission (route depth-first, then federation) order with stable
/// de-duplication. The host (a bundler plugin) registers these as watch
/// dependencies so editing a route file re-runs the virtual module.
///
/// Every emitted loader targets a route's `component_file`, falling back to its
/// `layout_file` — exactly the entry [`emit_route`] writes — so this list is the
/// authoritative record of what the emitted module depends on.
pub fn referenced_files(routing: &GeneratedRouting) -> Vec<String> {
    let mut files = Vec::new();
    for route in &routing.routes {
        collect_route_files(route, &mut files);
    }
    // Federation remotes carry their own entry files; include any not already
    // seen so the watch set is complete even if a remote points at a file no
    // route loader did (defensive — in practice remotes mirror route entries).
    for remote in &routing.remotes {
        push_unique(&mut files, &remote.entry_file);
    }
    files
}

/// Depth-first collect the loader entry file of `route` and its children.
fn collect_route_files(route: &AngularRoute, out: &mut Vec<String>) {
    if let Some(entry) = route.component_file.as_deref().or(route.layout_file.as_deref()) {
        push_unique(out, entry);
    }
    for child in &route.children {
        collect_route_files(child, out);
    }
}

/// Push `value` onto `out` only if not already present, preserving first-seen order.
fn push_unique(out: &mut Vec<String>, value: &str) {
    if !out.iter().any(|existing| existing == value) {
        out.push(value.to_string());
    }
}

/// Append one [`AngularRoute`] (and its children) as a TS `Route` object
/// literal at the given indent depth (one indent = one tab).
fn emit_route(out: &mut String, route: &AngularRoute, import_base: &str, indent: usize) {
    let pad = "\t".repeat(indent);
    let pad2 = "\t".repeat(indent + 1);

    out.push_str(&pad);
    out.push_str("{\n");

    out.push_str(&pad2);
    out.push_str("path: ");
    out.push_str(&json_string(&route.path));
    out.push_str(",\n");

    // A route's loader targets its component file, or — for a structural layout
    // parent — its layout file. Every emitted route has one of the two.
    if let Some(entry) = route.component_file.as_deref().or(route.layout_file.as_deref()) {
        out.push_str(&pad2);
        out.push_str("loadComponent: () => import(");
        out.push_str(&json_string(&join_import(import_base, entry)));
        out.push_str("),\n");
    }

    if !route.children.is_empty() {
        out.push_str(&pad2);
        out.push_str("children: [\n");
        for child in &route.children {
            emit_route(out, child, import_base, indent + 2);
        }
        out.push_str(&pad2);
        out.push_str("],\n");
    }

    out.push_str(&pad);
    out.push_str("},\n");
}

/// Append the `federationRemotes` array as a tab-indented JSON-ish object array
/// matching the JSON wire shape (`name` / `exposedModule` / `entryFile` /
/// `routePath`). Hand-rendered (rather than `serde_json`) so the indentation is
/// tabs and the field order is fixed and stable.
fn emit_remotes(out: &mut String, remotes: &[FederationRemote]) {
    if remotes.is_empty() {
        out.push_str("[]");
        return;
    }
    out.push_str("[\n");
    for (i, r) in remotes.iter().enumerate() {
        out.push_str("\t{\n");
        out.push_str("\t\t\"name\": ");
        out.push_str(&json_string(&r.name));
        out.push_str(",\n\t\t\"exposedModule\": ");
        out.push_str(&json_string(&r.exposed_module));
        out.push_str(",\n\t\t\"entryFile\": ");
        out.push_str(&json_string(&r.entry_file));
        out.push_str(",\n\t\t\"routePath\": ");
        out.push_str(&json_string(&r.route_path));
        out.push_str("\n\t}");
        if i + 1 < remotes.len() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push(']');
}

/// Join an `import(...)` loader path: `import_base` followed by the
/// tree-relative `entry` file. The base is used verbatim except that a single
/// separating `/` is ensured between a non-empty base and the entry (a base
/// already ending in `/` is not doubled; an empty base yields the entry alone).
fn join_import(import_base: &str, entry: &str) -> String {
    if import_base.is_empty() {
        entry.to_string()
    } else if import_base.ends_with('/') {
        format!("{import_base}{entry}")
    } else {
        format!("{import_base}/{entry}")
    }
}

/// Render `s` as a double-quoted JSON/TS string literal. The routing data only
/// ever contains path characters, but escaping `"` and `\` (and control chars)
/// keeps the emitted module well-formed for any input.
fn json_string(s: &str) -> String {
    // `serde_json` produces a spec-correct, deterministic double-quoted literal.
    serde_json::to_string(s).expect("string serialization is infallible")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{AngularRoute, FederationRemote, GeneratedRouting};

    fn route(path: &str, component: Option<&str>, layout: Option<&str>) -> AngularRoute {
        AngularRoute {
            path: path.to_string(),
            component_file: component.map(str::to_string),
            layout_file: layout.map(str::to_string),
            is_wildcard: path == "**",
            remote_name: None,
            children: Vec::new(),
        }
    }

    #[test]
    fn emits_routes_and_remotes_module() {
        let mut root = route("", None, Some("routes/layout.treaty"));
        root.children = vec![
            route("", Some("routes/index.treaty"), None),
            route("about", Some("routes/about.tjsx"), None),
        ];
        let routing = GeneratedRouting {
            routes: vec![root],
            remotes: vec![FederationRemote {
                name: "root".to_string(),
                exposed_module: "./Route".to_string(),
                entry_file: "routes/layout.treaty".to_string(),
                route_path: String::new(),
            }],
            endpoints: Vec::new(),
        };
        let ts = emit_ts(&routing, "../../");
        assert!(ts.contains("export const routes: Routes = ["));
        assert!(ts.contains("loadComponent: () => import(\"../../routes/layout.treaty\")"));
        assert!(ts.contains("loadComponent: () => import(\"../../routes/index.treaty\")"));
        assert!(ts.contains("path: \"about\""));
        assert!(ts.contains("export default routes"));
        assert!(ts.contains("export const federationRemotes = "));
        assert!(ts.trim_end().ends_with("as const"));
        // Deterministic.
        assert_eq!(ts, emit_ts(&routing, "../../"));
    }

    #[test]
    fn referenced_files_are_unique_and_depth_first() {
        let mut root = route("", None, Some("routes/layout.treaty"));
        root.children = vec![
            route("", Some("routes/index.treaty"), None),
            route("about", Some("routes/about.tjsx"), None),
        ];
        let routing = GeneratedRouting {
            routes: vec![root],
            remotes: vec![FederationRemote {
                name: "root".to_string(),
                exposed_module: "./Route".to_string(),
                // Mirrors the layout entry: must NOT duplicate.
                entry_file: "routes/layout.treaty".to_string(),
                route_path: String::new(),
            }],
            endpoints: Vec::new(),
        };
        let files = referenced_files(&routing);
        assert_eq!(
            files,
            vec![
                "routes/layout.treaty".to_string(),
                "routes/index.treaty".to_string(),
                "routes/about.tjsx".to_string(),
            ]
        );
    }

    #[test]
    fn empty_routing_emits_empty_remotes() {
        let ts = emit_ts(&GeneratedRouting::default(), "../../");
        assert!(ts.contains("export const routes: Routes = [\n]"));
        assert!(ts.contains("export const federationRemotes = [] as const"));
        assert!(referenced_files(&GeneratedRouting::default()).is_empty());
    }
}
