/**
 * Node smoke test for @treaty/rsbuild's file-routing virtual module wiring.
 *
 * File routing is produced DURING the build as a virtual module — there is no checked-in / prebuilt
 * routes.ts. The route graph is generated by the SHARED Rust-backed helper from @treaty/ts-vite
 * (the shim over the `treaty_file_routing` crate via @treaty/authoring-node.generateRoutes); this
 * package only adds the rsbuild-native wiring: an alias mapping `virtual:treaty-routes` to the
 * in-package sentinel plus an Rspack loader rule (via tools.rspack) that replaces the sentinel
 * source with the generated module.
 *
 * This does NOT run a full Rsbuild build (the bundler is a peer dependency and is not installed). It
 * asserts the contracts this package owns:
 *   1. with `fileRoutes` set, pluginTreaty aliases `virtual:treaty-routes` to the sentinel and adds
 *      the routes loader rule through tools.rspack — and adds NEITHER when `fileRoutes` is omitted;
 *   2. the routes loader, driven through the rspack loader contract over the real example app, emits
 *      a consumable Angular routes module and registers each referenced route file as a dependency;
 *   3. a missing routesRoot option fails the loader loudly.
 *
 * Run: node libs/treaty/rsbuild/test/routes-virtual.smoke.mjs
 */

import assert from 'node:assert/strict'
import { isAbsolute } from 'node:path'
import { fileURLToPath } from 'node:url'
import { pluginTreaty } from '../dist/plugin.js'
import {
	routesLoader,
	ROUTES_SENTINEL_TEST,
	routesSentinelPath,
	TREATY_ROUTES_ID,
} from '../dist/routes-virtual.js'

/** The real example app whose routes/ tree the loader lowers to an Angular route graph. */
const EXAMPLE_ROOT = fileURLToPath(new URL('../../../../examples/file-routed-app', import.meta.url))

let failures = 0
const results = []

function check(label, fn) {
	try {
		fn()
		results.push(`PASS ${label}`)
	} catch (err) {
		failures++
		results.push(`FAIL ${label}: ${err.message}`)
	}
}

/**
 * Drive a plugin's `setup` with a minimal Rsbuild API that records the config mutations the routes
 * wiring performs: it runs each `modifyRsbuildConfig` callback over a shared config, then resolves
 * the registered `tools.rspack` hook(s) over a fake rspack config to collect the module rules.
 * `api.transform` is omitted so the plugin takes the loader-rule fallback path (which is the only
 * path relevant to the routes wiring — the alias + tools.rspack rule are added regardless).
 */
function runSetup(plugin) {
	const config = {}
	const modifiers = []
	const api = {
		modifyRsbuildConfig(fn) {
			modifiers.push(fn)
		},
	}
	plugin.setup(api)
	for (const fn of modifiers) fn(config)

	// Resolve tools.rspack (a fn or array of fns) over a fake rspack config to gather rules.
	const rspackConfig = { module: { rules: [] } }
	const hooks = config.tools && config.tools.rspack
	const list = Array.isArray(hooks) ? hooks : hooks ? [hooks] : []
	for (const hook of list) hook(rspackConfig)
	return { config, rules: rspackConfig.module.rules }
}

// 1. with fileRoutes set, the plugin aliases the virtual id and adds the routes loader rule.
check('pluginTreaty wires the routes alias + loader rule when fileRoutes is set', () => {
	const { config, rules } = runSetup(pluginTreaty({ fileRoutes: { routesRoot: EXAMPLE_ROOT } }))

	const alias = config.resolve && config.resolve.alias
	assert.ok(alias && alias[TREATY_ROUTES_ID] === routesSentinelPath, 'virtual id aliased to sentinel')

	const rule = rules.find(
		(r) => r.use && r.use[0] && /routes-virtual-loader\.js$/.test(r.use[0].loader)
	)
	assert.ok(rule, 'a tools.rspack rule must point at the routes loader')
	assert.equal(rule.test, ROUTES_SENTINEL_TEST, 'rule matches the sentinel')
	assert.equal(rule.use[0].options.routesRoot, EXAMPLE_ROOT, 'loader carries the routesRoot option')
})

// 1b. without fileRoutes: no alias and no routes rule.
check('pluginTreaty adds no routes wiring when fileRoutes is omitted', () => {
	const { config, rules } = runSetup(pluginTreaty({}))
	assert.ok(
		!config.resolve || !config.resolve.alias || !(TREATY_ROUTES_ID in config.resolve.alias),
		'no routes alias without fileRoutes'
	)
	const rule = rules.find(
		(r) => r.use && r.use[0] && /routes-virtual-loader\.js$/.test(r.use[0].loader)
	)
	assert.ok(!rule, 'no routes loader rule without fileRoutes')
})

// 2. the loader generates the real route module and registers route files as deps.
check('routes loader emits a consumable route module + registers watch deps', () => {
	const deps = []
	let cbErr
	let code
	const ctx = {
		getOptions: () => ({ routesRoot: EXAMPLE_ROOT }),
		addDependency: (f) => deps.push(f),
		callback: (err, content) => {
			cbErr = err
			code = content
		},
	}
	routesLoader.call(ctx)
	assert.ok(!cbErr, `loader must not error: ${cbErr && cbErr.message}`)
	assert.ok(typeof code === 'string' && /\bexport\b[\s\S]*\broutes\b/.test(code), 'emits routes module')
	assert.ok(code.includes('export default routes'), 'emits default export')
	assert.ok(code.includes('loadComponent'), 'lazy route loaders present')
	// The shared shim down-levels the route module to plain JS so Rspack can parse it
	// without a TS loader: no `import type`, no `: Routes`, no `as const`.
	assert.ok(!/\bimport\s+type\b/.test(code), 'no TS-only import type in served JS')
	assert.ok(!/\bconst\s+routes\s*:/.test(code), 'no TS type annotation on the routes const')
	assert.ok(!/\bas\s+const\b/.test(code), 'no trailing TS `as const` assertion')
	assert.ok(deps.length > 0 && deps.every((f) => isAbsolute(f)), 'absolute route deps registered')
})

// 3. a missing routesRoot fails the loader loudly.
check('routes loader errors when routesRoot is missing', () => {
	let cbErr
	routesLoader.call({ getOptions: () => ({}), callback: (err) => (cbErr = err) })
	assert.ok(cbErr instanceof Error && /routesRoot/.test(cbErr.message), 'missing routesRoot errors')
})

for (const line of results) console.log(line)
if (failures > 0) {
	console.error(`\nSMOKE TEST FAILED: ${failures} case(s) failed`)
	process.exit(1)
}
console.log('\nSMOKE TEST PASSED')
