[workspace]
resolver = '2'
members = [
	'libs/authoring/node',
	'libs/authoring/treaty_authoring',
	'libs/render3',
	'libs/treaty-ivy/core',
	'libs/treaty-ivy/template',
	'libs/treaty-ivy/decorators',
	'apps/rust/authoring',
	'libs/runtime',
	'apps/treaty-cli',
	'libs/packagr',
	'tools/node-conformance',
]

[profile.release]
lto = true
