/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CompiledComponent {
  code: string
  errors: string[]
}
export function compileComponent(template: string, selector: string, className: string): CompiledComponent
export function compileComponentSource(source: string): CompiledComponent
export function compileTreatyFile(source: string, fileName: string): CompiledComponent
