/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Result of compiling a component template to Ivy. */
export interface CompiledComponent {
  /** The emitted JavaScript (the `ɵɵdefineComponent({...})` definition). */
  code: string
  /** Parse/transform diagnostics (empty on success). */
  errors: Array<string>
  /**
   * The additive Source Map v3 JSON mapping `code` back to the original source, or `undefined`
   * when the underlying path produced no map (e.g. the template-only `compileComponent` entry).
   */
  map?: string
}
/**
 * Compile an Angular component template directly to Ivy via the Rust/OXC `render3` compiler.
 *
 * `template` is the HTML template source, `selector` the component selector
 * (e.g. `"app-hello"`), and `class_name` the component class identifier.
 */
export declare function compileComponent(template: string, selector: string, className: string): CompiledComponent
/**
 * Compile an Angular `@Component`/`@Directive` class directly from its TypeScript SOURCE.
 *
 * `source` is the full TS file (or snippet) containing exactly one decorated class. Returns the
 * emitted `ɵɵdefineComponent({...})` definition plus the additive Source Map v3 JSON (`map`), or a
 * `CompiledComponent` carrying a descriptive error for shapes the source front-end does not yet
 * support (providers, queries, host bindings, `templateUrl`, multi-class files, etc.).
 */
export declare function compileComponentSource(source: string): CompiledComponent
/**
 * Compile a `.treaty` single-file component directly from its source.
 *
 * `source` is the full `.treaty` file contents and `file_name` its path/name (used for
 * diagnostics). Returns the emitted `ɵɵdefineComponent({...})` definition, or a
 * `CompiledComponent` carrying descriptive errors.
 */
export declare function compileTreatyFile(source: string, fileName: string): CompiledComponent
/** Result of the unified per-file authoring compile ([`compile`]). */
export interface CompiledAuthoring {
  /**
   * The compiled client module (the `ɵɵdefineComponent({...})` output, or — for a faithful
   * pass-through `.ts`/`.json`/etc. — the original source unchanged).
   */
  code: string
  /**
   * The generated backend module when the source declared a `server { … }` block; otherwise
   * `undefined`.
   */
  serverModule?: string
  /** Parse/transform diagnostics (empty on success). */
  errors: Array<string>
  /**
   * The additive Source Map v3 JSON mapping `code` back to the original authoring source, or
   * `undefined` when the routed front-end produced no map. CLIENT PRIVACY: when a `server { … }`
   * block was present, every lifted server-fn body has been redacted from the map's
   * `sourcesContent` before this field is populated.
   */
  map?: string
}
/**
 * Unified per-file authoring compile: route `source` to the right front-end by `file_name`'s
 * extension and return the compiled client module (+ optional server module + diagnostics).
 *
 * Extension routing (via `rust_authoring`'s `AuthoringRegistry`):
 *   * `.treaty` → the `.treaty` SFC front-end.
 *   * `.tsx` / `.tjsx` → the JSX front-end, which handles BARE JSX
 *     (`export default function App() { return <div/> }`) as well as `@Component` JSX — closing
 *     the gap left by [`compile_component_source`], which only accepts `@Component`.
 *   * `.ts` → the base-Angular front-end: `@Component` classes compile to `ɵɵdefineComponent`
 *     (server-block aware); `@Directive`/`@Pipe`/`@Injectable`/`@NgModule` and plain non-Angular
 *     modules pass through unchanged.
 *   * any other extension → passed through unchanged.
 */
export declare function compile(source: string, fileName: string): CompiledAuthoring
/** One file to compile in a [`compile_many`] batch. */
export interface AuthoringFile {
  /**
   * Caller-supplied identifier echoed back on the result (the file path/name). It is also used as
   * the routing `file_name` (its extension selects the front-end), so it must carry the real
   * extension (e.g. `"src/App.tsx"`, `"greeting.treaty"`).
   */
  id: string
  /** The full source of the file. */
  code: string
}
/**
 * One compiled file in a [`compile_many`] batch — the [`CompiledAuthoring`] result tagged with its
 * originating [`AuthoringFile::id`].
 */
export interface CompiledAuthoringEntry {
  /** The `id` of the input file this result corresponds to (echoed verbatim). */
  id: string
  /** The compiled client module (or faithful pass-through source). */
  code: string
  /**
   * The generated backend module when the source declared a `server { … }` block; otherwise
   * `undefined`.
   */
  serverModule?: string
  /** Parse/transform diagnostics (empty on success). */
  errors: Array<string>
  /**
   * The additive Source Map v3 JSON mapping `code` back to the original authoring source, or
   * `undefined` when the routed front-end produced no map. Server-fn bodies are redacted from the
   * map's `sourcesContent` (client privacy), exactly as for the single-file `compile` entry.
   */
  map?: string
}
/**
 * Compile many authoring files IN PARALLEL across all available cores.
 *
 * Each file is routed and compiled by [`rust_authoring::authoring::compile_file`] exactly as the
 * single-file [`compile`] entry does — `.treaty` / `.tsx` / `.tjsx` / `.ts` to their front-ends,
 * any other extension passed through unchanged. The work is fanned out with `rayon` because each
 * compile is CPU-bound, fully synchronous, and self-contained: every call builds its own oxc
 * `Allocator`/arena and shares no mutable global state, so the compiles run safely in parallel on
 * separate worker threads (the compiler's `thread_local!` scratch tables are per-thread and reset
 * at the start of each pass).
 *
 * Results are returned in INPUT ORDER regardless of completion order, each tagged with its input
 * `id`.
 */
export declare function compileMany(files: Array<AuthoringFile>): Array<CompiledAuthoringEntry>
/**
 * Execute a Treaty macro through the Nova-backed `treaty_runtime` and return its produced value
 * as a JSON string.
 *
 * `tsSource` is the TypeScript body of a macro (the top-of-file fenced block in a `.treaty` file).
 * `inputJson` is a JSON string injected as the macro's `input` / `__args` globals (pass `"null"`
 * for no input). The returned string is the JSON encoding of the macro's produced value (its
 * default export, explicit `return`, or trailing expression); values with no JSON form encode as
 * `null`.
 *
 * Throws if `inputJson` is not valid JSON, the source cannot be transpiled, or the macro throws.
 */
export declare function runMacro(tsSource: string, inputJson: string): string
/**
 * Execute a Treaty server function through the Nova-backed `treaty_runtime` and return its result
 * as a JSON string.
 *
 * `tsSource` is the TypeScript body of a server function; `argsJson` is a JSON string (typically an
 * array of positional arguments) injected as the function's `args` / `__args` globals. The returned
 * string is the JSON encoding of the value the function returns (or its trailing expression).
 *
 * Throws if `argsJson` is not valid JSON, the source cannot be transpiled, or the function throws.
 */
export declare function runServerFn(tsSource: string, argsJson: string): string
