/**
 * Node smoke test for @treaty/vite's file-routing virtual module wiring.
 *
 * File routing is produced DURING the build as a virtual module — there is no checked-in / prebuilt
 * routes.ts. The route graph is generated by the SHARED Rust-backed helper from @treaty/ts-vite
 * (the shim over the `treaty_file_routing` crate via @treaty/authoring-node.generateRoutes); this
 * package only adds the Vite resolveId/load wiring around it. The SAME helper backs @treaty/rspack
 * and @treaty/rsbuild, so the route output is identical across bundlers.
 *
 * It asserts the contracts this package owns:
 *   1. `treaty({ fileRoutes })` adds the routes plugin (enforce: 'pre', resolveId/load/handleHotUpdate)
 *      and `treaty()` (no fileRoutes) does NOT, so non-file-routed apps are unaffected;
 *   2. resolveId('virtual:treaty-routes') -> the resolved virtual id, and load() of that id returns
 *      the generated Angular routes module over the real example app + registers route watch files;
 *   3. resolveId returns null for unrelated ids (the plugin only claims the routes virtual module);
 *   4. handleHotUpdate invalidates the routes virtual module so a route edit regenerates it in dev.
 *
 * Run: node libs/treaty/vite/test/routes-virtual.smoke.mjs
 */

import assert from 'node:assert/strict'
import { isAbsolute } from 'node:path'
import { fileURLToPath } from 'node:url'
import treaty from '../dist/index.js'

const ROUTES_ID = 'virtual:treaty-routes'
const RESOLVED_ID = '\0virtual:treaty-routes'
const EXAMPLE_ROOT = fileURLToPath(new URL('../../../../examples/file-routed-app', import.meta.url))

let failures = 0
const results = []

function check(label, fn) {
	try {
		fn()
		results.push(`PASS ${label}`)
	} catch (err) {
		failures++
		results.push(`FAIL ${label}: ${err.stack ?? err.message}`)
	}
}

/** Find the file-routes plugin in a `treaty(...)` plugin array, or undefined. */
function routesPluginOf(plugins) {
	return plugins.find((p) => p && p.name === 'treaty:vite:file-routes')
}

// 1. fileRoutes toggles the routes plugin on/off.
check('treaty({ fileRoutes }) adds the routes plugin; treaty() does not', () => {
	const withRoutes = routesPluginOf(treaty({ fileRoutes: { routesRoot: EXAMPLE_ROOT } }))
	assert.ok(withRoutes, 'routes plugin present when fileRoutes is set')
	assert.equal(withRoutes.enforce, 'pre', 'routes plugin runs enforce: pre')
	assert.equal(typeof withRoutes.resolveId, 'function', 'resolveId hook present')
	assert.equal(typeof withRoutes.load, 'function', 'load hook present')
	assert.equal(typeof withRoutes.handleHotUpdate, 'function', 'handleHotUpdate hook present')

	assert.equal(routesPluginOf(treaty({})), undefined, 'no routes plugin without fileRoutes')
})

// 2. resolveId claims the virtual id; load returns the generated module + watch files.
check('resolveId -> resolved id, load -> generated route module over the example app', () => {
	const plugin = routesPluginOf(treaty({ fileRoutes: { routesRoot: EXAMPLE_ROOT } }))
	// configResolved captures the build root (used as cwd fallback); the example root is absolute
	// here so the value is irrelevant, but call it to mirror Vite's lifecycle.
	plugin.configResolved.call({}, { root: process.cwd() })

	const resolved = plugin.resolveId.call({}, ROUTES_ID)
	assert.equal(resolved, RESOLVED_ID, 'bare virtual id resolves to the resolved virtual id')

	const watched = []
	const loadCtx = { addWatchFile: (f) => watched.push(f) }
	const out = plugin.load.call(loadCtx, RESOLVED_ID)
	assert.ok(out && typeof out.code === 'string', 'load returns a { code } module')
	assert.ok(/\bexport\b[\s\S]*\broutes\b/.test(out.code), 'emits an Angular routes module')
	assert.ok(out.code.includes('export default routes'), 'emits a default export')
	assert.ok(out.code.includes('loadComponent'), 'lazy route loaders present')
	// The shared shim down-levels the module to plain JS so every bundler can parse
	// the virtual module directly: no TS-only `import type`, no `: Routes` annotation,
	// and no trailing `as const` survive.
	assert.ok(!/\bimport\s+type\b/.test(out.code), 'no TS-only import type in served JS')
	assert.ok(!/\bconst\s+routes\s*:/.test(out.code), 'no TS type annotation on the routes const')
	assert.ok(!/\bas\s+const\b/.test(out.code), 'no trailing TS `as const` assertion')
	assert.equal(out.map, null, 'load returns a null map (generated module needs none)')
	assert.ok(watched.length > 0, 'route entry files registered via addWatchFile')
	assert.ok(watched.every((f) => isAbsolute(f)), 'watch files are absolute paths')
})

// 3. resolveId ignores unrelated ids.
check('resolveId returns null for non-routes ids', () => {
	const plugin = routesPluginOf(treaty({ fileRoutes: { routesRoot: EXAMPLE_ROOT } }))
	assert.equal(plugin.resolveId.call({}, './app.ts'), null, 'unrelated id is not claimed')
	assert.equal(plugin.resolveId.call({}, 'virtual:other'), null, 'other virtual id is not claimed')
})

// 4. handleHotUpdate invalidates the routes virtual module so a route edit regenerates it.
check('handleHotUpdate invalidates the routes virtual module', () => {
	const plugin = routesPluginOf(treaty({ fileRoutes: { routesRoot: EXAMPLE_ROOT } }))
	const routesModule = { id: RESOLVED_ID }
	let invalidated
	let reloaded = false
	const changed = { id: '/x/routes/index.treaty' }
	const ctx = {
		modules: [changed],
		server: {
			moduleGraph: {
				getModuleById: (id) => (id === RESOLVED_ID ? routesModule : undefined),
				invalidateModule: (m) => (invalidated = m),
			},
			ws: { send: () => (reloaded = true) },
		},
	}
	const affected = plugin.handleHotUpdate.call({}, ctx)
	assert.equal(invalidated, routesModule, 'the routes virtual module is invalidated')
	assert.ok(reloaded, 'a full reload is signalled so the new route graph loads')
	assert.ok(Array.isArray(affected) && affected.includes(routesModule), 'routes module reported')
})

for (const line of results) console.log(line)
if (failures > 0) {
	console.error(`\nSMOKE TEST FAILED: ${failures} case(s) failed`)
	process.exit(1)
}
console.log('\nSMOKE TEST PASSED')
