/**
 * Node smoke test for @treaty/rspack's file-routing virtual module wiring.
 *
 * File routing is produced DURING the build as a virtual module — there is no checked-in / prebuilt
 * routes.ts. The route graph is generated by the SHARED Rust-backed helper from @treaty/ts-vite
 * (the shim over the `treaty_file_routing` crate via @treaty/authoring-node.generateRoutes); this
 * package only adds the rspack-native wiring: an alias mapping `virtual:treaty-routes` to the
 * in-package sentinel plus a loader rule that replaces the sentinel source with the generated module.
 *
 * This does NOT run a full Rspack build (the bundler is a peer dependency and is not installed). It
 * asserts the contracts this package owns:
 *   1. with `fileRoutes` set, the plugin aliases `virtual:treaty-routes` to the sentinel and adds the
 *      routes loader rule (matched to the sentinel) — and adds NEITHER when `fileRoutes` is omitted;
 *   2. the routes loader, driven through the rspack loader contract (getOptions + this.callback over
 *      the real example app), emits a consumable Angular routes module and registers each referenced
 *      route entry file as a build dependency (`this.addDependency`) for watch-mode regeneration;
 *   3. a missing routesRoot option fails the loader loudly.
 *
 * Run: node libs/treaty/rspack/test/routes-virtual.smoke.mjs
 */

import assert from 'node:assert/strict'
import { isAbsolute } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
	TreatyRspackPlugin,
	routesRule,
	routesLoader,
	ROUTES_SENTINEL_TEST,
	routesSentinelPath,
	TREATY_ROUTES_ID,
} from '../dist/index.js'

/** The real example app whose routes/ tree the loader lowers to an Angular route graph. */
const EXAMPLE_ROOT = fileURLToPath(new URL('../../../../examples/file-routed-app', import.meta.url))

let failures = 0
const results = []

function check(label, fn) {
	try {
		fn()
		results.push(`PASS ${label}`)
	} catch (err) {
		failures++
		results.push(`FAIL ${label}: ${err.message}`)
	}
}

// 1. with fileRoutes set, the plugin aliases the virtual id and adds the routes loader rule.
check('plugin wires the routes alias + loader rule when fileRoutes is set', () => {
	const plugin = new TreatyRspackPlugin({
		moduleFederation: false,
		fileRoutes: { routesRoot: EXAMPLE_ROOT },
	})
	const config = { module: {}, resolve: {} }
	plugin.apply({ options: config })

	const alias = config.resolve.alias
	assert.ok(alias && alias[TREATY_ROUTES_ID] === routesSentinelPath, 'virtual id aliased to sentinel')

	const rule = config.module.rules.find(
		(r) => r.use && r.use[0] && /routes-virtual-loader\.js$/.test(r.use[0].loader)
	)
	assert.ok(rule, 'a rule must point at the routes loader')
	assert.equal(rule.type, 'javascript/auto', 'routes rule uses javascript/auto')
	assert.ok(rule.test.test('/x/dist/routes-virtual-entry.js'), 'test matches the sentinel')
	assert.equal(rule.use[0].options.routesRoot, EXAMPLE_ROOT, 'loader carries the routesRoot option')
})

// 1b. without fileRoutes the plugin adds NO alias and NO routes rule (apps that do not file-route
// are unaffected).
check('plugin adds no routes wiring when fileRoutes is omitted', () => {
	const plugin = new TreatyRspackPlugin({ moduleFederation: false })
	const config = { module: {}, resolve: {} }
	plugin.apply({ options: config })
	assert.ok(
		!config.resolve.alias || !(TREATY_ROUTES_ID in config.resolve.alias),
		'no routes alias without fileRoutes'
	)
	const rule = (config.module.rules || []).find(
		(r) => r.use && r.use[0] && /routes-virtual-loader\.js$/.test(r.use[0].loader)
	)
	assert.ok(!rule, 'no routes loader rule without fileRoutes')
})

// 1c. routesRule() builder matches the sentinel and points at the loader with the given options.
check('routesRule builder matches the sentinel and carries options', () => {
	const rule = routesRule({ routesRoot: EXAMPLE_ROOT })
	assert.equal(rule.test, ROUTES_SENTINEL_TEST, 'exported sentinel test reused')
	assert.ok(/routes-virtual-loader\.js$/.test(rule.use[0].loader), 'points at routes loader')
	assert.equal(rule.use[0].options.routesRoot, EXAMPLE_ROOT, 'options forwarded')
})

// 2. the loader generates the real route module and registers route files as deps.
check('routes loader emits a consumable route module + registers watch deps', () => {
	const deps = []
	let cbErr
	let code
	const ctx = {
		getOptions: () => ({ routesRoot: EXAMPLE_ROOT }),
		addDependency: (f) => deps.push(f),
		callback: (err, content) => {
			cbErr = err
			code = content
		},
	}
	const ret = routesLoader.call(ctx)
	assert.equal(ret, undefined, 'with a callback the loader returns nothing')
	assert.ok(!cbErr, `loader must not error: ${cbErr && cbErr.message}`)
	assert.ok(typeof code === 'string' && code.includes('export const routes'), 'emits routes module')
	assert.ok(code.includes('export default routes'), 'emits default export')
	assert.ok(code.includes('loadComponent'), 'lazy route loaders present')
	assert.ok(deps.length > 0, 'route entry files registered as build deps')
	assert.ok(deps.every((f) => isAbsolute(f)), 'deps are absolute paths')
})

// 3. a missing routesRoot fails the loader loudly.
check('routes loader errors when routesRoot is missing', () => {
	let cbErr
	routesLoader.call({ getOptions: () => ({}), callback: (err) => (cbErr = err) })
	assert.ok(cbErr instanceof Error, 'missing routesRoot must produce a loader error')
	assert.match(cbErr.message, /routesRoot/, 'error names the missing option')
})

for (const line of results) console.log(line)
if (failures > 0) {
	console.error(`\nSMOKE TEST FAILED: ${failures} case(s) failed`)
	process.exit(1)
}
console.log('\nSMOKE TEST PASSED')
