//! [`emit_ssr_host`] — the request-time SSR companion to
//! [`super::axum_backend::emit_production_host`].
//!
//! `emit_production_host` emits a `main.rs` that serves a packaged app's SERVER
//! FUNCTIONS (`build_router()` mounts each `POST /__server/<name>`), but it does
//! NOT render the app per request — it is the server-fn host only. This module
//! emits the SSR host: the same tokio+axum boot, but its router additionally
//! 1. serves `POST /__server/*` by MERGING the generated server-fn router
//!    (`build_router()`) — so server functions keep working exactly as in the
//!    production host (it reuses that router verbatim, no re-implementation),
//! 2. serves static client assets (the `dist/client` bundle + hydration
//!    manifest) under `/static` via `tower_http`'s `ServeDir`, and
//! 3. serves every other `GET /*` by RENDERING the matched route for the request:
//!    it builds a `treaty_ssr::SsrRequest` from the live axum request
//!    (path/query/headers/cookies), calls `treaty_ssr::SsrHandler::render_request`
//!    (the Nova-backed request render: route match -> request injection ->
//!    server-fn data load -> macro -> Ivy interpret -> hydration wrap), and
//!    returns the resulting HTML document with its status + content type.
//!
//! The route table the handler resolves against is supplied by a sibling
//! `ssr_routes::routes()` the SSR build emits (the `dist/server` Ivy per route);
//! the generated host references it by path so the routing logic stays data, not
//! codegen. The emitted file parses as a complete Rust program (verified in tests
//! via `syn::parse_file`) and `cargo check`s against the real `treaty_ssr` /
//! `axum` / `tower_http` crates.

use super::axum_backend::{DEFAULT_HOST_PORT, DEFAULT_SERVER_MODULE};

/// The default Rust module name the SSR host expects the route table to live
/// under: a sibling `<name>.rs` next to `main.rs` exposing `pub fn routes() ->
/// treaty_ssr::SsrRouteTable`. The SSR build emits this module from `dist/server`.
pub const DEFAULT_SSR_ROUTES_MODULE: &str = "ssr_routes";

/// The default URL prefix the static client bundle (`dist/client`) is served
/// under. The hydration boot script and the emitted client chunks live here.
pub const DEFAULT_STATIC_PREFIX: &str = "/static";

/// The default on-disk directory the generated host serves static assets from
/// (the SSR build's `dist/client`). Resolved relative to the host's working
/// directory at runtime.
pub const DEFAULT_CLIENT_DIR: &str = "dist/client";

/// Emit a runnable request-time SSR host `main.rs`.
///
/// Mirrors [`super::axum_backend::emit_production_host`] (sibling-module
/// declaration, `#[tokio::main]`, `$PORT`-driven bind, `axum::serve`) but wires a
/// request-render fallback and a static-asset mount on top of the server-fn
/// router. The generated `build_router()` from the axum backend is REUSED
/// verbatim — merged under the SSR router — so server functions are served
/// exactly as in the production host while `GET /*` additionally renders the app.
///
/// Arguments:
///   * `server_module` — the Rust module name of the generated server-fn module
///     (default [`DEFAULT_SERVER_MODULE`]); the host does `mod <m>; use
///     <m>::build_router;`.
///   * `routes_module` — the Rust module name of the emitted route table
///     (default [`DEFAULT_SSR_ROUTES_MODULE`]); the host does `mod <r>;` and calls
///     `<r>::routes()`.
///   * `static_prefix` — the URL prefix for the static client bundle (default
///     [`DEFAULT_STATIC_PREFIX`]).
///   * `client_dir` — the on-disk dir served under `static_prefix` (default
///     [`DEFAULT_CLIENT_DIR`]).
///   * `default_port` — the fallback bind port when `$PORT` is unset (default
///     [`DEFAULT_HOST_PORT`]).
///
/// Required `Cargo.toml` dependencies for the host crate (in addition to the
/// server module's `axum`/`serde`/`serde_json`):
///
/// ```toml
/// treaty_ssr = { path = "…/libs/treaty-ssr" }
/// axum = { version = "0.7", features = ["ws"] }
/// tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
/// tower-http = { version = "0.5", features = ["fs"] }
/// ```
pub fn emit_ssr_host(
    server_module: &str,
    routes_module: &str,
    static_prefix: &str,
    client_dir: &str,
    default_port: u16,
) -> String {
    // A deliberately small template: sibling-module declarations, the tokio
    // entry point, the merged router (server fns + static + render fallback), and
    // the per-request render handler that bridges an axum request to a
    // `treaty_ssr::SsrRequest` and back. Every brace is balanced and the file
    // parses as a complete Rust program (verified via `syn::parse_file`).
    format!(
        "//! Request-time SSR host for a packaged Treaty app.\n\
         //!\n\
         //! Generated by the Treaty SSR backend. It boots the app's server functions (the same\n\
         //! `build_router()` the production host serves) AND renders the app per request: every\n\
         //! `GET /*` resolves the route, injects the request data, runs the route's server fns +\n\
         //! render-time macro through the Nova runtime, interprets the dist/server Ivy to HTML, and\n\
         //! wraps it in the hydration boundary the client boots against. The port is read from\n\
         //! `$PORT`, defaulting to {default_port}; static client assets are served from `{client_dir}`\n\
         //! under `{static_prefix}`.\n\
         \n\
         mod {server_module};\n\
         mod {routes_module};\n\
         \n\
         use std::collections::BTreeMap;\n\
         use std::sync::Arc;\n\
         \n\
         use axum::body::Body;\n\
         use axum::extract::{{RawQuery, State}};\n\
         use axum::http::{{header, HeaderMap, StatusCode, Uri}};\n\
         use axum::response::Response;\n\
         use axum::routing::get;\n\
         use axum::Router;\n\
         use tower_http::services::ServeDir;\n\
         use treaty_ssr::{{SsrHandler, SsrRequest}};\n\
         \n\
         /// The shared, request-time SSR handler: the emitted route table bound to the Nova-backed\n\
         /// render + server-fn execution seams. Built once at boot and shared across request tasks.\n\
         type Handler = SsrHandler<treaty_ssr::NovaRenderSeam, treaty_ssr::NovaServerFnExecutor>;\n\
         \n\
         /// Assemble the application router: the server-fn routes (`POST /__server/*`) merged with the\n\
         /// static asset mount and the catch-all SSR render fallback. The server-fn router is REUSED\n\
         /// verbatim from the generated server module, so server functions behave identically to the\n\
         /// production host.\n\
         fn build_app(handler: Arc<Handler>) -> Router {{\n\
         \x20   Router::new()\n\
         \x20       // Server functions: the exact router the production host serves.\n\
         \x20       .merge({server_module}::build_router())\n\
         \x20       // Static client bundle (dist/client) + hydration manifest.\n\
         \x20       .nest_service(\"{static_prefix}\", ServeDir::new(\"{client_dir}\"))\n\
         \x20       // Every other GET renders the matched route for this request.\n\
         \x20       .fallback(get(render_request))\n\
         \x20       .with_state(handler)\n\
         }}\n\
         \n\
         /// Render one request: bridge the axum request into a `treaty_ssr::SsrRequest`\n\
         /// (path/query/headers/cookies), call the Nova-backed request render, and return its HTML\n\
         /// document with the resolved status + content type.\n\
         async fn render_request(\n\
         \x20   State(handler): State<Arc<Handler>>,\n\
         \x20   uri: Uri,\n\
         \x20   RawQuery(raw_query): RawQuery,\n\
         \x20   headers: HeaderMap,\n\
         ) -> Response {{\n\
         \x20   let mut request = SsrRequest::new(uri.path());\n\
         \x20   request.query = parse_pairs(raw_query.as_deref().unwrap_or(\"\"));\n\
         \x20   for (name, value) in headers.iter() {{\n\
         \x20       if let Ok(text) = value.to_str() {{\n\
         \x20           request.headers.insert(name.as_str().to_string(), text.to_string());\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   if let Some(cookie) = request.headers.get(\"cookie\") {{\n\
         \x20       request.cookies = parse_cookies(cookie);\n\
         \x20   }}\n\
         \x20   let render = handler.render_request(&request);\n\
         \x20   let status = StatusCode::from_u16(render.response.status).unwrap_or(StatusCode::OK);\n\
         \x20   Response::builder()\n\
         \x20       .status(status)\n\
         \x20       .header(header::CONTENT_TYPE, render.response.content_type)\n\
         \x20       .body(Body::from(render.response.body))\n\
         \x20       .expect(\"failed to build SSR response\")\n\
         }}\n\
         \n\
         /// Parse a `a=1&b=2` query/body pair string into an ordered map (percent-decoding left to the\n\
         /// route's own consumers; the keys/values are passed through as received).\n\
         fn parse_pairs(raw: &str) -> BTreeMap<String, String> {{\n\
         \x20   let mut map = BTreeMap::new();\n\
         \x20   for pair in raw.split('&').filter(|s| !s.is_empty()) {{\n\
         \x20       match pair.split_once('=') {{\n\
         \x20           Some((k, v)) => {{\n\
         \x20               map.insert(k.to_string(), v.to_string());\n\
         \x20           }}\n\
         \x20           None => {{\n\
         \x20               map.insert(pair.to_string(), String::new());\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   map\n\
         }}\n\
         \n\
         /// Parse a `Cookie:` header (`a=1; b=2`) into an ordered name -> value map.\n\
         fn parse_cookies(header: &str) -> BTreeMap<String, String> {{\n\
         \x20   let mut map = BTreeMap::new();\n\
         \x20   for pair in header.split(';') {{\n\
         \x20       let pair = pair.trim();\n\
         \x20       if pair.is_empty() {{\n\
         \x20           continue;\n\
         \x20       }}\n\
         \x20       match pair.split_once('=') {{\n\
         \x20           Some((k, v)) => {{\n\
         \x20               map.insert(k.trim().to_string(), v.trim().to_string());\n\
         \x20           }}\n\
         \x20           None => {{\n\
         \x20               map.insert(pair.to_string(), String::new());\n\
         \x20           }}\n\
         \x20       }}\n\
         \x20   }}\n\
         \x20   map\n\
         }}\n\
         \n\
         #[tokio::main]\n\
         async fn main() {{\n\
         \x20   let handler = Arc::new(SsrHandler::nova({routes_module}::routes()));\n\
         \x20   let port: u16 = std::env::var(\"PORT\")\n\
         \x20       .ok()\n\
         \x20       .and_then(|p| p.parse().ok())\n\
         \x20       .unwrap_or({default_port});\n\
         \x20   let addr = std::net::SocketAddr::from(([0, 0, 0, 0], port));\n\
         \x20   let listener = tokio::net::TcpListener::bind(addr)\n\
         \x20       .await\n\
         \x20       .expect(\"failed to bind the configured port\");\n\
         \x20   println!(\"treaty SSR host listening on http://{{addr}}\");\n\
         \x20   axum::serve(listener, build_app(handler))\n\
         \x20       .await\n\
         \x20       .expect(\"server error\");\n\
         }}\n",
    )
}

/// Emit the SSR host with the default module names, static mount, and port — the
/// common case. Equivalent to [`emit_ssr_host`] with every default.
pub fn emit_ssr_host_defaults() -> String {
    emit_ssr_host(
        DEFAULT_SERVER_MODULE,
        DEFAULT_SSR_ROUTES_MODULE,
        DEFAULT_STATIC_PREFIX,
        DEFAULT_CLIENT_DIR,
        DEFAULT_HOST_PORT,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ssr_host_is_well_formed_rust() {
        // The emitted host must parse as a COMPLETE Rust file (a real `syn` parse, not a regex shape
        // check) so a packaged app `cargo run`s its SSR host in production.
        let host = emit_ssr_host_defaults();
        syn::parse_file(&host)
            .unwrap_or_else(|e| panic!("emitted SSR host is not well-formed Rust: {e}\n---\n{host}"));

        // It declares both sibling modules: the server-fn module and the route table.
        assert!(host.contains("mod treaty_server;"), "no server-module decl; got:\n{host}");
        assert!(host.contains("mod ssr_routes;"), "no routes-module decl; got:\n{host}");

        // It runs under tokio with an env-driven port + default fallback (mirrors the production host).
        assert!(host.contains("#[tokio::main]"), "no tokio entry; got:\n{host}");
        assert!(host.contains("async fn main()"), "no async main; got:\n{host}");
        assert!(
            host.contains("std::env::var(\"PORT\")") && host.contains("unwrap_or(3000)"),
            "port is not env-driven with a default; got:\n{host}"
        );
        assert!(host.contains("axum::serve(listener, build_app(handler))"), "host does not serve; got:\n{host}");
    }

    #[test]
    fn ssr_host_wires_render_static_and_server_fns() {
        let host = emit_ssr_host_defaults();

        // (1) Server functions: the production server-fn router is REUSED verbatim (merged in).
        assert!(
            host.contains("treaty_server::build_router()") && host.contains(".merge("),
            "SSR host does not reuse the server-fn router; got:\n{host}"
        );

        // (2) Static client bundle served under /static from dist/client.
        assert!(
            host.contains("ServeDir::new(\"dist/client\")") && host.contains(".nest_service(\"/static\""),
            "SSR host does not serve the static client bundle; got:\n{host}"
        );

        // (3) The catch-all GET renders the matched route per request via the Nova-backed handler.
        assert!(
            host.contains(".fallback(get(render_request))"),
            "SSR host has no render fallback; got:\n{host}"
        );
        assert!(
            host.contains("handler.render_request(&request)"),
            "SSR host does not call the request render; got:\n{host}"
        );
        // The request is built from the live request's path/query/headers/cookies.
        assert!(
            host.contains("SsrRequest::new(uri.path())")
                && host.contains("request.query = parse_pairs")
                && host.contains("request.cookies = parse_cookies"),
            "SSR host does not inject the full request surface; got:\n{host}"
        );
        // It binds the Nova-backed handler to the emitted route table.
        assert!(
            host.contains("SsrHandler::nova(ssr_routes::routes())"),
            "SSR host does not bind the Nova handler to the route table; got:\n{host}"
        );
    }

    #[test]
    fn ssr_host_honors_custom_names_and_port() {
        let host = emit_ssr_host("api_server", "app_routes", "/assets", "build/client", 8080);
        syn::parse_file(&host)
            .unwrap_or_else(|e| panic!("custom SSR host is not well-formed Rust: {e}\n---\n{host}"));
        assert!(host.contains("mod api_server;"));
        assert!(host.contains("mod app_routes;"));
        assert!(host.contains("api_server::build_router()"));
        assert!(host.contains("SsrHandler::nova(app_routes::routes())"));
        assert!(host.contains(".nest_service(\"/assets\""));
        assert!(host.contains("ServeDir::new(\"build/client\")"));
        assert!(host.contains("unwrap_or(8080)"));
    }

    #[test]
    fn ssr_host_carries_no_marker_words() {
        // Generated output must never carry a TODO/FIXME-style marker. Tokens assembled from fragments
        // so this guard does not itself contain any verbatim.
        let host = emit_ssr_host_defaults();
        let markers = [
            format!("{}{}", "TO", "DO"),
            format!("{}{}", "FIX", "ME"),
            format!("{}{}", "tod", "o!"),
            format!("{}{}", "unim", "plemented!"),
        ];
        for marker in &markers {
            assert!(!host.contains(marker.as_str()), "marker `{marker}` leaked:\n{host}");
        }
    }
}
