// End-to-end proof that file-based routing is GENERATED, not transcribed.
//
// This test runs the real generator (`scripts/generate-routes.mjs`, which builds
// and runs the detached `treaty_file_routing` CLI over THIS app's own routes/ +
// api/ tree) and then asserts the freshly written `src/generated/routes.ts`
// contains exactly the route paths, federation remotes, and api endpoints the
// on-disk directory tree implies. If a route file is added/renamed/removed and
// the engine is rerun, this test moves with it — there is no hand-maintained
// table to drift. A literal `routes.ts` (transcribed by hand) would fail the
// "regenerate then diff" guard below, because the content would not match what
// the engine produces from the current tree.
//
// Run: node test/routing.e2e.mjs   (or `npm run test:e2e`).
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import assert from 'node:assert/strict'

const here = dirname(fileURLToPath(import.meta.url))
const appRoot = join(here, '..')
const generator = join(appRoot, 'scripts', 'generate-routes.mjs')
const outFile = join(appRoot, 'src', 'generated', 'routes.ts')

/** Tiny test harness: collect pass/fail without extra deps. */
let failed = 0
const log = []
function test(name, fn) {
	try {
		fn()
		log.push(`OK   ${name}`)
	} catch (err) {
		failed++
		log.push(`FAIL ${name}\n  ${err.message.split('\n').join('\n  ')}`)
	}
}

// 1. Run the REAL generator end-to-end (cargo build + run the CLI over this app).
execFileSync(process.execPath, [generator], { cwd: appRoot, stdio: ['ignore', 'inherit', 'inherit'] })
const generated = readFileSync(outFile, 'utf8')

// Helper: assert a `path: "<p>"` line is present (the engine emits one tab-block
// route object per route, with `path:` then its lazy `loadComponent` loader).
function hasRoute(path, entryFile) {
	const pathLine = `path: ${JSON.stringify(path)}`
	assert.ok(generated.includes(pathLine), `missing route ${JSON.stringify(path)} (${pathLine})`)
	const loader = `import(${JSON.stringify(`../../${entryFile}`)})`
	assert.ok(generated.includes(loader), `missing lazy loader ${loader} for route ${JSON.stringify(path)}`)
}

// --- 2. The route graph reflects the routes/ tree, with Angular-native params --

test('it is the engine-generated artifact, not a hand-written file', () => {
	assert.ok(
		generated.startsWith('// GENERATED by `treaty-file-routing'),
		'generated file is missing the engine banner — it must be produced by the CLI, not edited by hand',
	)
	assert.ok(generated.includes('export const routes: Routes = ['), 'missing the Angular routes export')
	assert.ok(generated.includes('export default routes'), 'missing default export of routes')
})

test('root layout + index map to the root layout/index files at path ""', () => {
	// routes/layout.treaty -> the single top-level parent route at "".
	hasRoute('', 'routes/layout.treaty')
	// routes/index.treaty -> the landing page, a "" child of the root layout.
	hasRoute('', 'routes/index.treaty')
})

test('(marketing) route group is STRIPPED from the URL', () => {
	// (marketing)/index.treaty -> "" (group name contributes no segment).
	hasRoute('', 'routes/(marketing)/index.treaty')
	// (marketing)/about.tjsx -> "about", NOT "(marketing)/about".
	hasRoute('about', 'routes/(marketing)/about.tjsx')
	assert.ok(
		!/path:\s*"[^"]*\(marketing\)[^"]*"/.test(generated),
		'a route path still contains the (marketing) group name — it must be stripped',
	)
})

test('blog layout nests its children under "blog"', () => {
	hasRoute('blog', 'routes/blog/layout.treaty')
	hasRoute('', 'routes/blog/index.treaty')
})

test('blog/[slug] lowers to the Angular param :slug', () => {
	hasRoute(':slug', 'routes/blog/[slug]/index.treaty')
})

test('blog/[...path] catch-all directory lowers to a rest segment', () => {
	// A catch-all DIRECTORY lowers to a dynamic segment in the chosen style
	// (colon => :...path); only a not-found FILE produces the ** wildcard.
	hasRoute(':...path', 'routes/blog/[...path]/index.treaty')
})

test('deep nested docs/[category]/[page] lowers to docs/:category/:page', () => {
	hasRoute('docs/:category/:page', 'routes/docs/[category]/[page]/index.tjsx')
})

test('not-found lowers to the ** wildcard route', () => {
	hasRoute('**', 'routes/not-found.treaty')
})

// --- 3. Federation remotes mirror every lazy route + layout boundary ----------

test('federation remotes carry the unique de-duplicated names', () => {
	assert.ok(generated.includes('export const federationRemotes = ['), 'missing federationRemotes export')
	for (const name of [
		'root',
		'root-index',
		'root-marketing',
		'about',
		'blog',
		'root-blog',
		'path',
		'slug',
		'docs-category-page',
		'not-found',
	]) {
		assert.ok(
			generated.includes(`"name": ${JSON.stringify(name)}`),
			`missing federation remote "${name}"`,
		)
	}
	assert.ok(generated.includes('"exposedModule": "./Route"'), 'remotes must expose ./Route')
})

// --- 4. API endpoints mirror the api/ tree ------------------------------------

test('api endpoints are generated from the api/ tree with :param dynamics', () => {
	assert.ok(
		generated.includes('export const apiEndpoints: readonly ApiEndpoint[] = ['),
		'missing apiEndpoints export',
	)
	for (const [path, handlerFile] of [
		['/', 'api/index.ts'],
		['/health', 'api/health/index.ts'],
		['/posts', 'api/posts/index.ts'],
		['/posts/:id', 'api/posts/[id]/index.ts'],
	]) {
		assert.ok(generated.includes(`"path": ${JSON.stringify(path)}`), `missing api endpoint ${path}`)
		assert.ok(
			generated.includes(`"handlerFile": ${JSON.stringify(handlerFile)}`),
			`missing api handler ${handlerFile}`,
		)
	}
	// The dynamic /posts/:id endpoint records its parameter name.
	assert.ok(generated.includes('"id"'), 'missing :id param name on /posts/:id endpoint')
})

// --- 5. Generation is deterministic / idempotent (no transcription drift) -----

test('re-running the generator produces byte-identical output', () => {
	execFileSync(process.execPath, [generator], { cwd: appRoot, stdio: ['ignore', 'ignore', 'inherit'] })
	const again = readFileSync(outFile, 'utf8')
	assert.equal(again, generated, 'generator is not deterministic — output changed on a second run')
})

console.log(log.join('\n'))
console.log(failed ? `\n${failed} test(s) failed` : `\nAll ${log.length} routing e2e checks passed`)
process.exit(failed ? 1 : 0)
