/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate a complete static site, returning the [`treaty_ssg::GeneratedSite`]
 * as JSON: every prerendered page's full HTML document, plus the emitted
 * `sitemap.xml`, `robots.txt`, and hydration-manifest artifacts and the
 * in-memory hydration manifest.
 *
 * `config_json` is a `SsgConfig`; `render_inputs_json` is the routes config,
 * the static param sets, and the per-URL pre-resolved render inputs (see
 * [`RenderInputs`]). All SSG logic runs in the Rust core; this binding only
 * (de)serializes. Deterministic: identical inputs yield byte-identical JSON.
 */
export declare function generateSite(configJson: string, renderInputsJson: string): string
/**
 * Alias of [`generate_site`] under the core's pipeline name, so JS callers can
 * invoke the binding by the same name as the Rust entry point
 * (`prerenderSite`). Identical behaviour and output.
 */
export declare function prerenderSite(configJson: string, renderInputsJson: string): string
