/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Generate a complete static site, returning the [`treaty_ssg::GeneratedSite`]
 * as JSON: every prerendered page's full HTML document, plus the emitted
 * `sitemap.xml`, `robots.txt`, and hydration-manifest artifacts and the
 * in-memory hydration manifest.
 *
 * `config_json` is a `SsgConfig`; `render_inputs_json` is the routes config,
 * the static param sets, and the per-URL pre-resolved render inputs (see
 * [`RenderInputs`]). All SSG logic runs in the Rust core; this binding only
 * (de)serializes. Deterministic: identical inputs yield byte-identical JSON.
 */
export declare function generateSite(configJson: string, renderInputsJson: string): string
/**
 * Alias of [`generate_site`] under the core's pipeline name, so JS callers can
 * invoke the binding by the same name as the Rust entry point
 * (`prerenderSite`). Identical behaviour and output.
 */
export declare function prerenderSite(configJson: string, renderInputsJson: string): string
/**
 * Enumerate every concrete, prerenderable route from a routes config, returning
 * the [`treaty_ssg::DiscoveredRoute`] list (`url`, `route_path`, `parameterized`,
 * `params`) as JSON.
 *
 * The deterministic discovery walk — static + parameterized fan-out, wildcard /
 * pure-redirect dropping, recursive children — runs entirely in
 * [`treaty_ssg::discovery`]. The TS shim re-attaches each route node (the
 * non-serializable `route` field of its `DiscoveredRoute`) to the result, since
 * a route node carries function-valued loaders that cannot cross JSON.
 */
export declare function discoverRoutes(discoverInputsJson: string): string
/**
 * Render a `sitemap.xml` document for the entries, resolving each `url` against
 * `origin` into an absolute `<loc>`. Pure pass-through to
 * [`treaty_ssg::manifest::build_sitemap`]; deterministic and minimal.
 */
export declare function buildSitemap(sitemapInputsJson: string): string
/**
 * Render a `robots.txt` body (a single `User-agent: *` group with any disallow
 * prefixes, optionally advertising a sitemap). Pure pass-through to
 * [`treaty_ssg::manifest::build_robots`].
 */
export declare function buildRobots(robotsInputsJson: string): string
/**
 * Join a site `origin` with a root-relative `url_path` into one absolute,
 * deduplicated-slash location (an already-absolute `http(s)://…` path passes
 * through). Pure pass-through to [`treaty_ssg::manifest::absolute_url`].
 */
export declare function absoluteUrl(origin: string, urlPath: string): string
/**
 * Statically interpret emitted Ivy JS for one component into an HTML fragment,
 * binding interpolations against `data_json` (a JSON object of render data, or
 * `{}`). Returns the empty string when `ivy_code` carries no recognizable
 * template function (a pass-through module), matching the TS `renderIvyToHtml`.
 *
 * The interpretation runs entirely in [`treaty_ssg::ivy_html`]; this binding
 * only parses the render data and stringifies the fragment. A non-object
 * `data_json` (or invalid JSON) surfaces as a thrown error so the shim sees a
 * precise message.
 */
export declare function renderIvyToHtml(ivyCode: string, dataJson: string): string
/**
 * Generate a complete static site from a config + a fully-resolved page list,
 * returning the [`treaty_ssg::GeneratedSite`] as JSON.
 *
 * This is the entry the `@treaty/ssg` shim drives. The shim has already (a)
 * discovered the routes (via [`discover_routes`]), (b) compiled each route's
 * component to Ivy and run its render-time macro through the Nova runtime to
 * resolve the render data, and (c) resolved the `title` / `head` /
 * `sitemapEntry` callbacks of the TS `SiteConfig` to plain values. This binding
 * then drives the pure `treaty_ssg` modules to do every byte of emit:
 * [`ivy_html`] interprets each template to an HTML fragment + detects its
 * hydration islands, [`seo`] resolves the head and wraps the fragment into a
 * full hydration-ready document, and [`manifest`] emits `sitemap.xml`,
 * `robots.txt`, and the hydration manifest (each gated by the config). No SSG
 * decision is made here — the binding only sequences the core's pure functions.
 * Deterministic: identical inputs yield byte-identical JSON.
 */
export declare function generateSiteFull(siteInputsJson: string): string
