// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Text = 1,
  attributeContentSingle = 33,
  attributeContentDouble = 34,
  scriptAttributeContentSingle = 35,
  scriptAttributeContentDouble = 36,
  Content = 2,
  Interpolation = 5,
  InterpolationContent = 6,
  Entity = 7,
  InvalidEntity = 8,
  Attribute = 9,
  Identifier = 12,
  Is = 18,
  AttributeValue = 27
